[protodef.plugin_example]
post = 'echo "Hello World"'
version = '0.0.1'
out = 'python_plugin_example'


[protodef.python_plugin_litestar]
post = 'echo "Hello World"'
version = '0.0.1'
out = 'python_plugin_example'
